SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        google_sub TEXT NOT NULL UNIQUE,
        email TEXT NOT NULL,
        name TEXT NOT NULL,
        avatar_url TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_login_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS portfolios (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        base_currency TEXT NOT NULL DEFAULT 'EUR',
        source_filename TEXT,
        source_portfolio_id INTEGER,
        derived_from TEXT,
        effective_start_date TEXT,
        baseline_invested_capital DOUBLE PRECISION,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_portfolios_user
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_portfolios_source
            FOREIGN KEY (source_portfolio_id) REFERENCES portfolios(id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS portfolio_transactions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        portfolio_id INTEGER NOT NULL,
        date TEXT,
        ticker TEXT,
        type TEXT NOT NULL,
        quantity DOUBLE PRECISION,
        total_amount TEXT,
        total_amount_original_curr TEXT,
        currency TEXT,
        raw_json TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_transactions_portfolio
            FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS portfolio_imports (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        portfolio_id INTEGER NOT NULL,
        filename TEXT,
        uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        row_count INTEGER NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'pending',
        CONSTRAINT fk_imports_portfolio
            FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS market_prices (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ticker TEXT NOT NULL,
        date DATE NOT NULL,
        open DOUBLE PRECISION,
        high DOUBLE PRECISION,
        low DOUBLE PRECISION,
        close DOUBLE PRECISION,
        adjusted_close DOUBLE PRECISION,
        volume DOUBLE PRECISION,
        exchange TEXT,
        currency TEXT,
        provider TEXT NOT NULL DEFAULT 'eodhd',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_market_prices_ticker_date UNIQUE (ticker, date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS market_data_download_locks (
        ticker TEXT PRIMARY KEY,
        started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ticker_symbol_mappings (
        input_ticker TEXT PRIMARY KEY,
        provider_ticker TEXT NOT NULL,
        exchange TEXT,
        currency TEXT,
        resolution_source TEXT NOT NULL DEFAULT 'seed',
        confirmed BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_users_google_sub ON users(google_sub)",
    "CREATE INDEX IF NOT EXISTS idx_portfolios_user_id ON portfolios(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_transactions_portfolio_id ON portfolio_transactions(portfolio_id)",
    "CREATE INDEX IF NOT EXISTS idx_imports_portfolio_id ON portfolio_imports(portfolio_id)",
    "CREATE INDEX IF NOT EXISTS idx_market_prices_ticker_date ON market_prices(ticker, date)",
    "CREATE INDEX IF NOT EXISTS idx_market_data_download_locks_started_at ON market_data_download_locks(started_at)",
    "CREATE INDEX IF NOT EXISTS idx_ticker_symbol_mappings_provider_ticker ON ticker_symbol_mappings(provider_ticker)",
)


POST_SCHEMA_MIGRATIONS = (
    "ALTER TABLE portfolio_transactions ADD COLUMN IF NOT EXISTS total_amount_original_curr TEXT",
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS source_portfolio_id INTEGER",
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS derived_from TEXT",
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS effective_start_date TEXT",
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS baseline_invested_capital DOUBLE PRECISION",
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_portfolios_source'
        ) THEN
            ALTER TABLE portfolios
            ADD CONSTRAINT fk_portfolios_source
            FOREIGN KEY (source_portfolio_id) REFERENCES portfolios(id) ON DELETE SET NULL;
        END IF;
    END
    $$;
    """,
)


TICKER_MAPPING_SEED_ROWS = [
    ("EXI2", "EXI2.XETRA", "XETRA", "EUR"),
    ("IS3Q", "IS3Q.XETRA", "XETRA", "EUR"),
    ("AMEM", "AMEM.XETRA", "XETRA", "EUR"),
    ("XDWT", "XDWT.XETRA", "XETRA", "EUR"),
    ("DBXJ", "DBXJ.XETRA", "XETRA", "EUR"),
    ("IS3K", "IS3K.XETRA", "XETRA", "EUR"),
    ("EXW1", "EXW1.XETRA", "XETRA", "EUR"),
    ("XUCD", "XUCD.XETRA", "XETRA", "EUR"),
    ("SXR8", "SXR8.XETRA", "XETRA", "EUR"),
    ("AAPL", "AAPL.US", "US", "USD"),
    ("MSFT", "MSFT.US", "US", "USD"),
    ("NVDA", "NVDA.US", "US", "USD"),
    ("GOOGL", "GOOGL.US", "US", "USD"),
    ("GOOG", "GOOG.US", "US", "USD"),
    ("AMZN", "AMZN.US", "US", "USD"),
    ("META", "META.US", "US", "USD"),
    ("TSLA", "TSLA.US", "US", "USD"),
    ("AMD", "AMD.US", "US", "USD"),
    ("AVGO", "AVGO.US", "US", "USD"),
    ("NFLX", "NFLX.US", "US", "USD"),
    ("BRK-B", "BRK-B.US", "US", "USD"),
    ("JPM", "JPM.US", "US", "USD"),
    ("V", "V.US", "US", "USD"),
    ("MA", "MA.US", "US", "USD"),
    ("KO", "KO.US", "US", "USD"),
    ("PEP", "PEP.US", "US", "USD"),
    ("JNJ", "JNJ.US", "US", "USD"),
    ("PG", "PG.US", "US", "USD"),
    ("UNH", "UNH.US", "US", "USD"),
    ("COST", "COST.US", "US", "USD"),
    ("QQQ", "QQQ.US", "US", "USD"),
    ("SPY", "SPY.US", "US", "USD"),
    ("VTI", "VTI.US", "US", "USD"),
    ("VXUS", "VXUS.US", "US", "USD"),
    ("IWM", "IWM.US", "US", "USD"),
    ("BABA", "BABA.US", "US", "USD"),
    ("JD", "JD.US", "US", "USD"),
    ("NIO", "NIO.US", "US", "USD"),
    ("PDD", "PDD.US", "US", "USD"),
    ("TSM", "TSM.US", "US", "USD"),
    ("NESN", "NESN.SW", "SW", "CHF"),
    ("NOVN", "NOVN.SW", "SW", "CHF"),
    ("UBSG", "UBSG.SW", "SW", "CHF"),
    ("ROG", "ROG.SW", "SW", "CHF"),
    ("ASML", "ASML.AS", "AS", "EUR"),
    ("MC", "MC.PA", "PA", "EUR"),
    ("AIR", "AIR.PA", "PA", "EUR"),
    ("SAN", "SAN.PA", "PA", "EUR"),
    ("SU", "SU.PA", "PA", "EUR"),
    ("CEZ", "CEZ.PR", "PR", "CZK"),
    ("KOMB", "KOMB.PR", "PR", "CZK"),
    ("MONET", "MONET.PR", "PR", "CZK"),
    ("7203", "7203.TSE", "TSE", "JPY"),
    ("6758", "6758.TSE", "TSE", "JPY"),
    ("7974", "7974.TSE", "TSE", "JPY"),
    ("9984", "9984.TSE", "TSE", "JPY"),
    ("9988", "9988.HK", "HK", "HKD"),
    ("0700", "0700.HK", "HK", "HKD"),
    ("SAP", "SAP.XETRA", "XETRA", "EUR"),
    ("SIE", "SIE.XETRA", "XETRA", "EUR"),
    ("ALV", "ALV.XETRA", "XETRA", "EUR"),
]
