SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        google_sub TEXT NOT NULL UNIQUE,
        email TEXT NOT NULL,
        name TEXT NOT NULL,
        avatar_url TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_login_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS portfolios (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        base_currency TEXT NOT NULL DEFAULT 'EUR',
        source_filename TEXT,
        source_portfolio_id INTEGER,
        derived_from TEXT,
        effective_start_date TEXT,
        baseline_invested_capital DOUBLE PRECISION,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_portfolios_user
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_portfolios_source
            FOREIGN KEY (source_portfolio_id) REFERENCES portfolios(id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS portfolio_transactions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        portfolio_id INTEGER NOT NULL,
        date TEXT,
        ticker TEXT,
        type TEXT NOT NULL,
        quantity DOUBLE PRECISION,
        total_amount TEXT,
        currency TEXT,
        raw_json TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_transactions_portfolio
            FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS portfolio_imports (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        portfolio_id INTEGER NOT NULL,
        filename TEXT,
        uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        row_count INTEGER NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'pending',
        CONSTRAINT fk_imports_portfolio
            FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS market_prices (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ticker TEXT NOT NULL,
        date DATE NOT NULL,
        open DOUBLE PRECISION,
        high DOUBLE PRECISION,
        low DOUBLE PRECISION,
        close DOUBLE PRECISION,
        adjusted_close DOUBLE PRECISION,
        volume DOUBLE PRECISION,
        exchange TEXT,
        currency TEXT,
        provider TEXT NOT NULL DEFAULT 'eodhd',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_market_prices_ticker_date UNIQUE (ticker, date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS market_data_download_locks (
        ticker TEXT PRIMARY KEY,
        started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_users_google_sub ON users(google_sub)",
    "CREATE INDEX IF NOT EXISTS idx_portfolios_user_id ON portfolios(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_transactions_portfolio_id ON portfolio_transactions(portfolio_id)",
    "CREATE INDEX IF NOT EXISTS idx_imports_portfolio_id ON portfolio_imports(portfolio_id)",
    "CREATE INDEX IF NOT EXISTS idx_market_prices_ticker_date ON market_prices(ticker, date)",
    "CREATE INDEX IF NOT EXISTS idx_market_data_download_locks_started_at ON market_data_download_locks(started_at)",
)


POST_SCHEMA_MIGRATIONS = (
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS source_portfolio_id INTEGER",
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS derived_from TEXT",
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS effective_start_date TEXT",
    "ALTER TABLE portfolios ADD COLUMN IF NOT EXISTS baseline_invested_capital DOUBLE PRECISION",
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_portfolios_source'
        ) THEN
            ALTER TABLE portfolios
            ADD CONSTRAINT fk_portfolios_source
            FOREIGN KEY (source_portfolio_id) REFERENCES portfolios(id) ON DELETE SET NULL;
        END IF;
    END
    $$;
    """,
)
